#!/usr/bin/env python3
# Copyright 2026 FancyAI
# SPDX-License-Identifier: Apache-2.0

"""
Crop a 3x3 storyboard image into 9 individual panels and resize to video resolution.

Usage:
    python3 crop_storyboard.py STORYBOARD_IMAGE OUTPUT_DIR [--width 720] [--height 1280] [--trim 8]

Reads a single storyboard image (generated by nano-banana), splits it into a
3x3 grid of panels, trims panel border whitespace, resizes each panel to the
target video resolution, and saves as panel_1.png through panel_9.png.
"""

import argparse
import os
from PIL import Image


GRID_COLS = 3
GRID_ROWS = 3


def crop_storyboard(image_path, output_dir, target_width=720, target_height=1280,
                    border_trim_px=8):
    """Crop storyboard into individual panels and resize to video resolution.

    Returns list of saved file paths in reading order (left-to-right, top-to-bottom).
    """
    img = Image.open(image_path)
    panel_w = img.width // GRID_COLS
    panel_h = img.height // GRID_ROWS

    os.makedirs(output_dir, exist_ok=True)
    paths = []
    for row in range(GRID_ROWS):
        for col in range(GRID_COLS):
            idx = row * GRID_COLS + col + 1
            box = (
                col * panel_w + border_trim_px,
                row * panel_h + border_trim_px,
                (col + 1) * panel_w - border_trim_px,
                (row + 1) * panel_h - border_trim_px,
            )
            panel = img.crop(box).resize(
                (target_width, target_height), Image.LANCZOS
            )
            out_path = os.path.join(output_dir, f"panel_{idx}.png")
            panel.save(out_path)
            paths.append(out_path)
            print(f"Saved: {out_path} ({target_width}x{target_height})")

    print(f"\nCropped {len(paths)} panels from {image_path}")
    return paths


def main():
    parser = argparse.ArgumentParser(description="Crop 3x3 storyboard into panels")
    parser.add_argument("image", help="Path to storyboard image")
    parser.add_argument("output_dir", help="Directory to save cropped panels")
    parser.add_argument("--width", type=int, default=720, help="Target panel width (default: 720)")
    parser.add_argument("--height", type=int, default=1280, help="Target panel height (default: 1280)")
    parser.add_argument("--trim", type=int, default=8, help="Border trim in pixels (default: 8)")
    args = parser.parse_args()

    crop_storyboard(args.image, args.output_dir, args.width, args.height, args.trim)


if __name__ == "__main__":
    main()
